/**
 * AVIRA Language Configuration
 * Central registry for all supported languages and their UI translations.
 */

export type LangCode = 'en' | 'hi' | 'mr'

export interface LanguageConfig {
  name: string
  nativeName: string
  speechCode: string   // BCP-47 for Web Speech API (e.g. 'hi-IN')
  ttsLang: string      // For gTTS / browser TTS
  flag: string          // Visible label
}

export const LANGUAGES: Record<LangCode, LanguageConfig> = {
  en: { name: 'English',  nativeName: 'English',  speechCode: 'en-IN', ttsLang: 'en', flag: 'EN' },
  hi: { name: 'Hindi',    nativeName: 'हिन्दी',    speechCode: 'hi-IN', ttsLang: 'hi', flag: 'HI' },
  mr: { name: 'Marathi',  nativeName: 'मराठी',     speechCode: 'mr-IN', ttsLang: 'mr', flag: 'MR' },
}

export const DEFAULT_LANG: LangCode = 'en'

/**
 * UI string translations for every visible label in AVIRA.
 */
export const UI_STRINGS: Record<LangCode, Record<string, string>> = {
  en: {
    // Greeting
    greeting: "Good day! I'm AVIRA, your personal care assistant. I'm ready to help you with music, appliances, the time, or just a friendly chat. If you ever need urgent help, press the red SOS button. How can I help you today?",
    // Dashboard
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    conversations: 'Conversations',
    alertsToday: 'Alerts Today',
    healthScore: 'Health Score',
    devicesOn: 'Devices On',
    sosButton: 'SOS Emergency',
    cancelSos: 'Cancel SOS',
    sosActive: 'EMERGENCY ALERT ACTIVE',
    sosHelp: 'Help is on the way! Stay calm.',
    // Input
    inputPlaceholder: 'Type a message or speak...',
    send: 'Send',
    listening: 'Listening...',
    speaking: 'Speaking...',
    // System Status
    voiceInput: 'Voice Input',
    textToSpeech: 'Text-to-Speech',
    smartHome: 'Smart Home',
    sosSystem: 'SOS System',
    internet: 'Internet',
    available: 'Available',
    active: 'Active',
    ready: 'Ready',
    online: 'Online',
    // Activity
    activityLog: 'Activity Log',
    // Language
    language: 'Language',
    selectLanguage: 'Select Language',
    stopListening: 'Stop listening',
    startListening: 'Start voice input',
    footer_status: 'All appliances ready • Voice commands active • 24/7 monitoring enabled — AVIRA Phase 1',
    clickToSpeak: 'Click orb to speak',
    emergencySosTitle: 'Emergency SOS',
    activeAlert: 'ACTIVE',
    cancelAlert: 'CANCEL ALERT',
    emergencySosAction: 'EMERGENCY SOS',
    sosInstruction: 'Say "Help me" or press for urgent help',
    notifyingCaregivers: 'Notifying caregivers… ID:',
    sosAlertDescription: 'Caregiver notification dispatched.',
    simulatedSms: 'Simulated SMS + Log dispatched',
    systemStatusTitle: 'System Status',
    quickCommands: 'Quick Commands',
    cmd_time: 'Time',
    cmd_date: 'Date',
    cmd_music: 'Music',
    cmd_youtube: 'YouTube',
    cmd_google: 'Google',
    cmd_joke: 'Joke',
    cmd_funFact: 'Fun Fact',
    cmd_weather: 'Weather',
    cmd_hindiSongs: 'Hindi Songs',
    cmd_lightsOn: 'All Lights ON',
    cmd_lightsOff: 'Lights OFF',
    cmd_tvOn: 'TV ON',
    cmd_lockDoor: 'Lock Door',
    cmd_whatsapp: 'Whatsapp',
    smartHomeTitle: 'Smart Home Control',
    activeCount: 'Active',
    allOn: 'All ON',
    allOff: 'All OFF',
    livingRoom: 'Living Room',
    bedroom: 'Bedroom',
    entrance: 'Entrance',
    brightness: 'Brightness',
    speed: 'Speed',
    on: 'ON',
    off: 'OFF',
    locked: 'LOCKED',
    open: 'OPEN',
    turned: 'turned',
    allLightsTurned: 'All lights turned',
  },

  hi: {
    greeting: "नमस्ते! मैं AVIRA हूँ, आपकी व्यक्तिगत देखभाल सहायक। मैं संगीत, उपकरण, समय, या बस एक अच्छी बातचीत में आपकी मदद के लिए तैयार हूँ। अगर आपको कभी तत्काल मदद चाहिए, तो लाल SOS बटन दबाएँ। आज मैं आपकी कैसे मदद कर सकती हूँ?",
    dashboard: 'डैशबोर्ड',
    analytics: 'विश्लेषण',
    conversations: 'बातचीत',
    alertsToday: 'आज की चेतावनी',
    healthScore: 'स्वास्थ्य स्कोर',
    devicesOn: 'चालू उपकरण',
    sosButton: 'SOS आपातकालीन',
    cancelSos: 'SOS रद्द करें',
    sosActive: 'आपातकालीन चेतावनी सक्रिय',
    sosHelp: 'मदद आ रही है! शांत रहें।',
    inputPlaceholder: 'संदेश लिखें या बोलें...',
    send: 'भेजें',
    listening: 'सुन रहा है...',
    speaking: 'बोल रहा है...',
    voiceInput: 'आवाज़ इनपुट',
    textToSpeech: 'टेक्स्ट-टू-स्पीच',
    smartHome: 'स्मार्ट होम',
    sosSystem: 'SOS सिस्टम',
    internet: 'इंटरनेट',
    available: 'उपलब्ध',
    active: 'सक्रिय',
    ready: 'तैयार',
    online: 'ऑनलाइन',
    activityLog: 'गतिविधि लॉग',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    stopListening: 'सुनना बंद करें',
    startListening: 'आवाज़ इनपुट शुरू करें',
    footer_status: 'सभी उपकरण तैयार • वॉयस कमांड सक्रिय • 24/7 निगरानी सक्षम — AVIRA चरण 1',
    clickToSpeak: 'बोलने के लिए ऑर्ब पर क्लिक करें',
    emergencySosTitle: 'आपातकालीन SOS',
    activeAlert: 'सक्रिय',
    cancelAlert: 'अलर्ट रद्द करें',
    emergencySosAction: 'आपातकालीन SOS',
    sosInstruction: 'तत्काल मदद के लिए "मेरी मदद करो" कहें या दबाएँ',
    notifyingCaregivers: 'देखभाल करने वालों को सूचित कर रहा है… ID:',
    sosAlertDescription: 'देखभाल करने वाले को सूचना भेज दी गई है।',
    simulatedSms: 'सिम्युलेटेड SMS + लॉग भेजा गया',
    systemStatusTitle: 'सिस्टम स्थिति',
    quickCommands: 'त्वरित कमांड',
    cmd_time: 'समय',
    cmd_date: 'तारीख',
    cmd_music: 'संगीत',
    cmd_youtube: 'यूट्यूब',
    cmd_google: 'गूगल',
    cmd_joke: 'चुटकुला',
    cmd_funFact: 'रोचक तथ्य',
    cmd_weather: 'मौसम',
    cmd_hindiSongs: 'हिंदी गाने',
    cmd_lightsOn: 'सभी लाइटें चालू',
    cmd_lightsOff: 'लाइटें बंद',
    cmd_tvOn: 'टीवी चालू',
    cmd_lockDoor: 'दरवाज़ा बंद',
    cmd_whatsapp: 'व्हाट्सएप',
    smartHomeTitle: 'स्मार्ट होम कंट्रोल',
    activeCount: 'सक्रिय',
    allOn: 'सभी चालू',
    allOff: 'सभी बंद',
    livingRoom: 'दीवान खाना',
    bedroom: 'शयनकक्ष',
    entrance: 'प्रवेश द्वार',
    brightness: 'चमक',
    speed: 'गति',
    on: 'चालू',
    off: 'बंद',
    locked: 'बंद',
    open: 'खुला',
    turned: 'हो गया',
    allLightsTurned: 'सभी लाइटें',
  },

  mr: {
    greeting: "नमस्कार! मी AVIRA आहे, तुमची वैयक्तिक काळजी सहाय्यक। मी संगीत, उपकरणे, वेळ, किंवा फक्त एक छान गप्पा मारण्यासाठी तयार आहे. तुम्हाला कधी तत्काळ मदत हवी असल्यास, लाल SOS बटण दाबा. आज मी तुमची कशी मदत करू शकते?",
    dashboard: 'डॅशबोर्ड',
    analytics: 'विश्लेषण',
    conversations: 'संभाषणे',
    alertsToday: 'आजचे अलर्ट',
    healthScore: 'आरोग्य स्कोर',
    devicesOn: 'चालू उपकरणे',
    sosButton: 'SOS आणीबाणी',
    cancelSos: 'SOS रद्द करा',
    sosActive: 'आणीबाणी अलर्ट सक्रिय',
    sosHelp: 'मदत येत आहे! शांत रहा.',
    inputPlaceholder: 'संदेश टाइप करा किंवा बोला...',
    send: 'पाठवा',
    listening: 'ऐकत आहे...',
    speaking: 'बोलत आहे...',
    voiceInput: 'आवाज इनपुट',
    textToSpeech: 'टेक्स्ट-टू-स्पीच',
    smartHome: 'स्मार्ट होम',
    sosSystem: 'SOS सिस्टम',
    internet: 'इंटरनेट',
    available: 'उपलब्ध',
    active: 'सक्रिय',
    ready: 'तयार',
    online: 'ऑनलाइन',
    activityLog: 'क्रियाकलाप लॉग',
    language: 'भाषा',
    selectLanguage: 'भाषा निवडा',
    stopListening: 'ऐकणे थांबवा',
    startListening: 'आवाज इनपुट सुरू करा',
    footer_status: 'सर्व उपकरणे तयार • व्हॉईस कमांड सक्रिय • 24/7 मॉनिटरिंग सक्षम — AVIRA टप्पा 1',
    clickToSpeak: 'बोलण्यासाठी ऑर्बवर क्लिक करा',
    emergencySosTitle: 'आणीबाणी SOS',
    activeAlert: 'सक्रिय',
    cancelAlert: 'अलर्ट रद्द करा',
    emergencySosAction: 'आणीबाणी SOS',
    sosInstruction: 'तातडीच्या मदतीसाठी "मला मदत करा" म्हणा किंवा दाबा',
    notifyingCaregivers: 'काळजी घेणाऱ्यांना सूचित करत आहे… ID:',
    sosAlertDescription: 'काळजी घेणाऱ्याला सूचना पाठवण्यात आली आहे.',
    simulatedSms: 'सिम्युलेटेड SMS + लॉग पाठवला',
    systemStatusTitle: 'सिस्टम स्थिती',
    quickCommands: 'त्वरित कमांड',
    cmd_time: 'वेळ',
    cmd_date: 'तारीख',
    cmd_music: 'संगीत',
    cmd_youtube: 'यूट्यूब',
    cmd_google: 'गूगल',
    cmd_joke: 'विनोद',
    cmd_funFact: 'रोचक तथ्य',
    cmd_weather: 'हवामान',
    cmd_hindiSongs: 'हिंदी गाणी',
    cmd_lightsOn: 'सर्व दिवे चालू',
    cmd_lightsOff: 'दिवे बंद',
    cmd_tvOn: 'टीव्ही चालू',
    cmd_lockDoor: 'दरवाजा बंद',
    cmd_whatsapp: 'व्हॉट्सॲप',
    smartHomeTitle: 'स्मार्ट होम कंट्रोल',
    activeCount: 'सक्रिय',
    allOn: 'सर्व चालू',
    allOff: 'सर्व बंद',
    livingRoom: 'बैठक खोली',
    bedroom: 'शयनकक्ष',
    entrance: 'प्रवेशद्वार',
    brightness: 'ब्राइटनेस',
    speed: 'वेग',
    on: 'चालू',
    off: 'बंद',
    locked: 'बंद',
    open: 'उघडा',
    turned: 'झाले',
    allLightsTurned: 'सर्व दिवे',
  },
}

/**
 * Caregiver Hub UI strings (used in vanilla JS caregiver/index.html)
 */
export const CAREGIVER_STRINGS: Record<string, Record<string, string>> = {
  en: {
    emotionalTelemetry: 'Emotional Telemetry',
    liveConversation: 'Live Conversation Stream',
    homeDevices: 'Home Devices',
    conversations: 'Conversations',
    sosEvents: 'SOS Events',
    reminders: 'Reminders',
    sendVoiceMessage: 'Send Voice Message',
    broadcastMessage: 'Broadcast Message',
    typeMessage: 'Type a custom message...',
    setReminder: 'Set Reminder',
    activeReminders: 'Active Reminders',
    reminderMessage: 'Reminder message...',
    healthReport: 'Health Report',
    todaysOverview: "Today's Overview",
    emotionBreakdown: 'Emotion Breakdown',
    aiModel: 'AI Model',
    fullConversationHistory: 'Full Conversation History',
    sentMessages: 'Sent Messages',
    comingHome: 'Coming home',
    takeMedicine: 'Take medicine',
    iLoveYou: 'I love you',
    eatenToday: 'Eaten today?',
    callingSoon: 'Calling soon',
    drinkWater: 'Drink water',
    messageDelivered: 'Message delivered to AVIRA',
    failedToSend: 'Failed to send — check connection',
    reminderSet: 'Reminder set!',
    noConversations: 'No conversations yet',
    noDevices: 'No devices',
    noReminders: 'No active reminders',
    noMessages: 'No messages sent yet',
    noEmotionData: 'No emotion data today',
    messageSpoken: 'Your message will be spoken aloud by AVIRA immediately.',
    reminderSpoken: 'AVIRA will speak the reminder aloud at the scheduled time.',
    systemLive: 'SYSTEM LIVE',
    offline: 'OFFLINE',
  },
  hi: {
    emotionalTelemetry: 'भावनात्मक टेलीमेट्री',
    liveConversation: 'लाइव बातचीत',
    homeDevices: 'घरेलू उपकरण',
    conversations: 'बातचीत',
    sosEvents: 'SOS घटनाएँ',
    reminders: 'रिमाइंडर',
    sendVoiceMessage: 'आवाज़ संदेश भेजें',
    broadcastMessage: 'संदेश प्रसारित करें',
    typeMessage: 'संदेश टाइप करें...',
    setReminder: 'रिमाइंडर सेट करें',
    activeReminders: 'सक्रिय रिमाइंडर',
    reminderMessage: 'रिमाइंडर संदेश...',
    healthReport: 'स्वास्थ्य रिपोर्ट',
    todaysOverview: 'आज का अवलोकन',
    emotionBreakdown: 'भावना विश्लेषण',
    aiModel: 'AI मॉडल',
    fullConversationHistory: 'पूर्ण बातचीत इतिहास',
    sentMessages: 'भेजे गए संदेश',
    comingHome: 'घर आ रहा हूँ',
    takeMedicine: 'दवाई लो',
    iLoveYou: 'मैं तुमसे प्यार करता हूँ',
    eatenToday: 'आज खाना खाया?',
    callingSoon: 'जल्दी कॉल करूँगा',
    drinkWater: 'पानी पियो',
    messageDelivered: 'AVIRA को संदेश पहुँचाया गया',
    failedToSend: 'भेजने में विफल — कनेक्शन जाँचें',
    reminderSet: 'रिमाइंडर सेट हो गया!',
    noConversations: 'अभी तक कोई बातचीत नहीं',
    noDevices: 'कोई उपकरण नहीं',
    noReminders: 'कोई सक्रिय रिमाइंडर नहीं',
    noMessages: 'अभी तक कोई संदेश नहीं भेजा',
    noEmotionData: 'आज कोई भावना डेटा नहीं',
    messageSpoken: 'आपका संदेश AVIRA द्वारा तुरंत बोला जाएगा।',
    reminderSpoken: 'AVIRA निर्धारित समय पर रिमाइंडर बोलेगा।',
    systemLive: 'सिस्टम चालू',
    offline: 'ऑफ़लाइन',
  },
  mr: {
    emotionalTelemetry: 'भावनात्मक टेलीमेट्री',
    liveConversation: 'थेट संभाषण',
    homeDevices: 'घरगुती उपकरणे',
    conversations: 'संभाषणे',
    sosEvents: 'SOS घटना',
    reminders: 'रिमाइंडर',
    sendVoiceMessage: 'आवाज संदेश पाठवा',
    broadcastMessage: 'संदेश प्रसारित करा',
    typeMessage: 'संदेश टाइप करा...',
    setReminder: 'रिमाइंडर सेट करा',
    activeReminders: 'सक्रिय रिमाइंडर',
    reminderMessage: 'रिमाइंडर संदेश...',
    healthReport: 'आरोग्य अहवाल',
    todaysOverview: 'आजचा आढावा',
    emotionBreakdown: 'भावना विश्लेषण',
    aiModel: 'AI मॉडेल',
    fullConversationHistory: 'संपूर्ण संभाषण इतिहास',
    sentMessages: 'पाठवलेले संदेश',
    comingHome: 'घरी येतोय',
    takeMedicine: 'औषध घ्या',
    iLoveYou: 'मी तुमच्यावर प्रेम करतो',
    eatenToday: 'आज जेवलात का?',
    callingSoon: 'लवकरच कॉल करतो',
    drinkWater: 'पाणी प्या',
    messageDelivered: 'AVIRA ला संदेश पोहोचला',
    failedToSend: 'पाठवणे अयशस्वी — कनेक्शन तपासा',
    reminderSet: 'रिमाइंडर सेट झाला!',
    noConversations: 'अजून कोणतेही संभाषण नाही',
    noDevices: 'कोणतेही उपकरण नाही',
    noReminders: 'कोणतेही सक्रिय रिमाइंडर नाही',
    noMessages: 'अजून कोणताही संदेश पाठवलेला नाही',
    noEmotionData: 'आज भावना डेटा नाही',
    messageSpoken: 'तुमचा संदेश AVIRA लगेच बोलेल.',
    reminderSpoken: 'AVIRA ठरलेल्या वेळी रिमाइंडर बोलेल.',
    systemLive: 'सिस्टम चालू',
    offline: 'ऑफलाइन',
  },
}
